# Generated by Django 3.2.12 on 2023-07-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddNotes',
            new_name='AddNote',
        ),
    ]
