# Generated by Django 3.2.12 on 2023-07-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_addnotes_addnote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddNote',
            new_name='AddNotes',
        ),
    ]
