# Generated by Django 4.2.3 on 2023-07-20 10:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_addnotes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnotes',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
